# name: GPTLens
# channels:
#   - defaults
# dependencies:
#   - bzip2=1.0.8=he774522_0
#   - ca-certificates=2023.12.12=haa95532_0
#   - libffi=3.4.4=hd77b12b_0
#   - openssl=3.0.13=h2bbff1b_0
#   - pip=23.3.1=py311haa95532_0
#   - python=3.11.7=he1021f5_0
#   - setuptools=68.2.2=py311haa95532_0
#   - sqlite=3.41.2=h2bbff1b_0
#   - tk=8.6.12=h2bbff1b_0
#   - vc=14.2=h21ff451_1
#   - vs2015_runtime=14.27.29016=h5e58377_2
#   # - wheel=0.41.2=py311haa95532_0
#   - xz=5.4.5=h8cc25b3_0
#   - zlib=1.2.13=h8cc25b3_0
#   - pip:
#       - aiohttp==3.9.3
#       - aiosignal==1.3.1
#       - altair==5.2.0
#       - annotated-types==0.6.0
#       - anyio==4.2.0
#       - attrs==23.2.0
#       - blinker==1.7.0
#       - cachetools==5.3.2
#       - certifi==2024.2.2
#       - charset-normalizer==3.3.2
#       - click==8.1.7
#       - colorama==0.4.6
#       - distro==1.9.0
#       - frozenlist==1.4.1
#       - gitdb==4.0.11
#       - gitpython==3.1.41
#       - h11==0.14.0
#       - httpcore==1.0.2
#       - httpx==0.26.0
#       - idna==3.6
#       - importlib-metadata==7.0.1
#       - inflection==0.5.1
#       - jinja2==3.1.3
#       - jsonschema==4.21.1
#       - jsonschema-specifications==2023.12.1
#       - markdown-it-py==3.0.0
#       - markupsafe==2.1.5
#       - mdurl==0.1.2
#       - multidict==6.0.5
#       - numpy==1.26.3
#       - openai==1.11.1
#       - openapi==1.1.0
#       - packaging==23.2
#       - pandas==2.2.0
#       - pillow==10.2.0
#       - protobuf==4.25.2
#       - pyarrow==15.0.0
#       - pydantic==2.6.0
#       - pydantic-core==2.16.1
#       - pydeck==0.8.1b0
#       - pygments==2.17.2
#       - python-dateutil==2.8.2
#       - pytz==2024.1
#       - referencing==0.33.0
#       - requests==2.31.0
#       - rich==13.7.0
#       - rpds-py==0.17.1
#       - six==1.16.0
#       - smmap==5.0.1
#       - sniffio==1.3.0
#       - streamlit==1.31.0
#       - tenacity==8.2.3
#       - toml==0.10.2
#       - toolz==0.12.1
#       - tornado==6.4
#       - tqdm==4.66.1
#       - typing-extensions==4.9.0
#       - tzdata==2023.4
#       - tzlocal==5.2
#       - urllib3==2.2.0
#       - validators==0.22.0
#       - watchdog==3.0.0
#       - yarl==1.9.4
#       - zipp==3.17.0
